module GL_VERSION_1_4
  @functions = @functions.merge( {
    glFogCoordd:             [ :void, :GLdouble ].freeze,
    glFogCoorddv:            [ :void, :pointer ].freeze,
    glFogCoordf:             [ :void, :GLfloat ].freeze,
    glFogCoordfv:            [ :void, :pointer ].freeze,
    glFogCoordPointer:       [ :void, :GLenum, :GLsizei, :pointer ].freeze,
    glSecondaryColor3b:      [ :void, :GLbyte, :GLbyte, :GLbyte ].freeze,
    glSecondaryColor3bv:     [ :void, :pointer ].freeze,
    glSecondaryColor3d:      [ :void, :GLdouble, :GLdouble, :GLdouble ].freeze,
    glSecondaryColor3dv:     [ :void, :pointer ].freeze,
    glSecondaryColor3f:      [ :void, :GLfloat, :GLfloat, :GLfloat ].freeze,
    glSecondaryColor3fv:     [ :void, :pointer ].freeze,
    glSecondaryColor3i:      [ :void, :GLint, :GLint, :GLint ].freeze,
    glSecondaryColor3iv:     [ :void, :pointer ].freeze,
    glSecondaryColor3s:      [ :void, :GLshort, :GLshort, :GLshort ].freeze,
    glSecondaryColor3sv:     [ :void, :pointer ].freeze,
    glSecondaryColor3ub:     [ :void, :GLubyte, :GLubyte, :GLubyte ].freeze,
    glSecondaryColor3ubv:    [ :void, :pointer ].freeze,
    glSecondaryColor3ui:     [ :void, :GLuint, :GLuint, :GLuint ].freeze,
    glSecondaryColor3uiv:    [ :void, :pointer ].freeze,
    glSecondaryColor3us:     [ :void, :GLushort, :GLushort, :GLushort ].freeze,
    glSecondaryColor3usv:    [ :void, :pointer ].freeze,
    glSecondaryColorPointer: [ :void, :GLint, :GLenum, :GLsizei, :pointer ].freeze,
    glWindowPos2d:           [ :void, :GLdouble, :GLdouble ].freeze,
    glWindowPos2dv:          [ :void, :pointer ].freeze,
    glWindowPos2f:           [ :void, :GLfloat, :GLfloat ].freeze,
    glWindowPos2fv:          [ :void, :pointer ].freeze,
    glWindowPos2i:           [ :void, :GLint, :GLint ].freeze,
    glWindowPos2iv:          [ :void, :pointer ].freeze,
    glWindowPos2s:           [ :void, :GLshort, :GLshort ].freeze,
    glWindowPos2sv:          [ :void, :pointer ].freeze,
    glWindowPos3d:           [ :void, :GLdouble, :GLdouble, :GLdouble ].freeze,
    glWindowPos3dv:          [ :void, :pointer ].freeze,
    glWindowPos3f:           [ :void, :GLfloat, :GLfloat, :GLfloat ].freeze,
    glWindowPos3fv:          [ :void, :pointer ].freeze,
    glWindowPos3i:           [ :void, :GLint, :GLint, :GLint ].freeze,
    glWindowPos3iv:          [ :void, :pointer ].freeze,
    glWindowPos3s:           [ :void, :GLshort, :GLshort, :GLshort ].freeze,
    glWindowPos3sv:          [ :void, :pointer ].freeze
  } ).freeze
end