module GL_VERSION_1_3
  @functions = @functions.merge( {
    glClientActiveTexture:  [ :void, :GLenum ].freeze,
    glLoadTransposeMatrixd: [ :void, :pointer ].freeze,
    glLoadTransposeMatrixf: [ :void, :pointer ].freeze,
    glMultiTexCoord1d:      [ :void, :GLenum, :GLdouble ].freeze,
    glMultiTexCoord1dv:     [ :void, :GLenum, :pointer ].freeze,
    glMultiTexCoord1f:      [ :void, :GLenum, :GLfloat ].freeze,
    glMultiTexCoord1fv:     [ :void, :GLenum, :pointer ].freeze,
    glMultiTexCoord1i:      [ :void, :GLenum, :GLint ].freeze,
    glMultiTexCoord1iv:     [ :void, :GLenum, :pointer ].freeze,
    glMultiTexCoord1s:      [ :void, :GLenum, :GLshort ].freeze,
    glMultiTexCoord1sv:     [ :void, :GLenum, :pointer ].freeze,
    glMultiTexCoord2d:      [ :void, :GLenum, :GLdouble, :GLdouble ].freeze,
    glMultiTexCoord2dv:     [ :void, :GLenum, :pointer ].freeze,
    glMultiTexCoord2f:      [ :void, :GLenum, :GLfloat, :GLfloat ].freeze,
    glMultiTexCoord2fv:     [ :void, :GLenum, :pointer ].freeze,
    glMultiTexCoord2i:      [ :void, :GLenum, :GLint, :GLint ].freeze,
    glMultiTexCoord2iv:     [ :void, :GLenum, :pointer ].freeze,
    glMultiTexCoord2s:      [ :void, :GLenum, :GLshort, :GLshort ].freeze,
    glMultiTexCoord2sv:     [ :void, :GLenum, :pointer ].freeze,
    glMultiTexCoord3d:      [ :void, :GLenum, :GLdouble, :GLdouble, :GLdouble ].freeze,
    glMultiTexCoord3dv:     [ :void, :GLenum, :pointer ].freeze,
    glMultiTexCoord3f:      [ :void, :GLenum, :GLfloat, :GLfloat, :GLfloat ].freeze,
    glMultiTexCoord3fv:     [ :void, :GLenum, :pointer ].freeze,
    glMultiTexCoord3i:      [ :void, :GLenum, :GLint, :GLint, :GLint ].freeze,
    glMultiTexCoord3iv:     [ :void, :GLenum, :pointer ].freeze,
    glMultiTexCoord3s:      [ :void, :GLenum, :GLshort, :GLshort, :GLshort ].freeze,
    glMultiTexCoord3sv:     [ :void, :GLenum, :pointer ].freeze,
    glMultiTexCoord4d:      [ :void, :GLenum, :GLdouble, :GLdouble, :GLdouble, :GLdouble ].freeze,
    glMultiTexCoord4dv:     [ :void, :GLenum, :pointer ].freeze,
    glMultiTexCoord4f:      [ :void, :GLenum, :GLfloat, :GLfloat, :GLfloat, :GLfloat ].freeze,
    glMultiTexCoord4fv:     [ :void, :GLenum, :pointer ].freeze,
    glMultiTexCoord4i:      [ :void, :GLenum, :GLint, :GLint, :GLint, :GLint ].freeze,
    glMultiTexCoord4iv:     [ :void, :GLenum, :pointer ].freeze,
    glMultiTexCoord4s:      [ :void, :GLenum, :GLshort, :GLshort, :GLshort, :GLshort ].freeze,
    glMultiTexCoord4sv:     [ :void, :GLenum, :pointer ].freeze,
    glMultTransposeMatrixd: [ :void, :pointer ].freeze,
    glMultTransposeMatrixf: [ :void, :pointer ].freeze
  } ).freeze
end