# Unlike other extensions, functions from this module are not pointers.

module GL_VERSION_1_0
  @functions = @functions.merge( {
    glAccum:             [ :void, :GLenum, :GLfloat ].freeze,
    glAlphaFunc:         [ :void, :GLenum, :GLfloat ].freeze,
    glBegin:             [ :void, :GLenum ].freeze,
    glBitmap:            [ :void, :GLsizei, :GLsizei, :GLfloat, :GLfloat, :GLfloat, :GLfloat, :pointer ].freeze,
    glCallList:          [ :void, :GLuint ].freeze,
    glCallLists:         [ :void, :GLsizei, :GLenum, :pointer ].freeze,
    glClearAccum:        [ :void, :GLfloat, :GLfloat, :GLfloat, :GLfloat ].freeze,
    glClearIndex:        [ :void, :GLfloat ].freeze,
    glClipPlane:         [ :void, :GLenum, :pointer ].freeze,
    glColor3b:           [ :void, :GLbyte, :GLbyte, :GLbyte ].freeze,
    glColor3bv:          [ :void, :pointer ].freeze,
    glColor3d:           [ :void, :GLdouble, :GLdouble, :GLdouble ].freeze,
    glColor3dv:          [ :void, :pointer ].freeze,
    glColor3f:           [ :void, :GLfloat, :GLfloat, :GLfloat ].freeze,
    glColor3fv:          [ :void, :pointer ].freeze,
    glColor3i:           [ :void, :GLint, :GLint, :GLint ].freeze,
    glColor3iv:          [ :void, :pointer ].freeze,
    glColor3s:           [ :void, :GLshort, :GLshort, :GLshort ].freeze,
    glColor3sv:          [ :void, :pointer ].freeze,
    glColor3ub:          [ :void, :GLubyte, :GLubyte, :GLubyte ].freeze,
    glColor3ubv:         [ :void, :pointer ].freeze,
    glColor3ui:          [ :void, :GLuint, :GLuint, :GLuint ].freeze,
    glColor3uiv:         [ :void, :pointer ].freeze,
    glColor3us:          [ :void, :GLushort, :GLushort, :GLushort ].freeze,
    glColor3usv:         [ :void, :pointer ].freeze,
    glColor4b:           [ :void, :GLbyte, :GLbyte, :GLbyte, :GLbyte ].freeze,
    glColor4bv:          [ :void, :pointer ].freeze,
    glColor4d:           [ :void, :GLdouble, :GLdouble, :GLdouble, :GLdouble ].freeze,
    glColor4dv:          [ :void, :pointer ].freeze,
    glColor4f:           [ :void, :GLfloat, :GLfloat, :GLfloat, :GLfloat ].freeze,
    glColor4fv:          [ :void, :pointer ].freeze,
    glColor4i:           [ :void, :GLint, :GLint, :GLint, :GLint ].freeze,
    glColor4iv:          [ :void, :pointer ].freeze,
    glColor4s:           [ :void, :GLshort, :GLshort, :GLshort, :GLshort ].freeze,
    glColor4sv:          [ :void, :pointer ].freeze,
    glColor4ub:          [ :void, :GLubyte, :GLubyte, :GLubyte, :GLubyte ].freeze,
    glColor4ubv:         [ :void, :pointer ].freeze,
    glColor4ui:          [ :void, :GLuint, :GLuint, :GLuint, :GLuint ].freeze,
    glColor4uiv:         [ :void, :pointer ].freeze,
    glColor4us:          [ :void, :GLushort, :GLushort, :GLushort, :GLushort ].freeze,
    glColor4usv:         [ :void, :pointer ].freeze,
    glColorMaterial:     [ :void, :GLenum, :GLenum ].freeze,
    glCopyPixels:        [ :void, :GLint, :GLint, :GLsizei, :GLsizei, :GLenum ].freeze,
    glDeleteLists:       [ :void, :GLuint, :GLsizei ].freeze,
    glDrawPixels:        [ :void, :GLsizei, :GLsizei, :GLenum, :GLenum, :pointer ].freeze,
    glEdgeFlag:          [ :void, :GLboolean ].freeze,
    glEdgeFlagv:         [ :void, :pointer ].freeze,
    glEnd:               [ :void ].freeze,
    glEndList:           [ :void ].freeze,
    glEvalCoord1d:       [ :void, :GLdouble ].freeze,
    glEvalCoord1dv:      [ :void, :pointer ].freeze,
    glEvalCoord1f:       [ :void, :GLfloat ].freeze,
    glEvalCoord1fv:      [ :void, :pointer ].freeze,
    glEvalCoord2d:       [ :void, :GLdouble, :GLdouble ].freeze,
    glEvalCoord2dv:      [ :void, :pointer ].freeze,
    glEvalCoord2f:       [ :void, :GLfloat, :GLfloat ].freeze,
    glEvalCoord2fv:      [ :void, :pointer ].freeze,
    glEvalMesh1:         [ :void, :GLenum, :GLint, :GLint ].freeze,
    glEvalMesh2:         [ :void, :GLenum, :GLint, :GLint, :GLint, :GLint ].freeze,
    glEvalPoint1:        [ :void, :GLint ].freeze,
    glEvalPoint2:        [ :void, :GLint, :GLint ].freeze,
    glFeedbackBuffer:    [ :void, :GLsizei, :GLenum, :pointer ].freeze,
    glFogf:              [ :void, :GLenum, :GLfloat ].freeze,
    glFogfv:             [ :void, :GLenum, :pointer ].freeze,
    glFogi:              [ :void, :GLenum, :GLint ].freeze,
    glFogiv:             [ :void, :GLenum, :pointer ].freeze,
    glFrustum:           [ :void, :GLdouble, :GLdouble, :GLdouble, :GLdouble, :GLdouble, :GLdouble ].freeze,
    glGenLists:          [ :GLuint, :GLsizei ].freeze,
    glGetClipPlane:      [ :void, :GLenum, :pointer ].freeze,
    glGetLightfv:        [ :void, :GLenum, :GLenum, :pointer ].freeze,
    glGetLightiv:        [ :void, :GLenum, :GLenum, :pointer ].freeze,
    glGetMapdv:          [ :void, :GLenum, :GLenum, :pointer ].freeze,
    glGetMapfv:          [ :void, :GLenum, :GLenum, :pointer ].freeze,
    glGetMapiv:          [ :void, :GLenum, :GLenum, :pointer ].freeze,
    glGetMaterialfv:     [ :void, :GLenum, :GLenum, :pointer ].freeze,
    glGetMaterialiv:     [ :void, :GLenum, :GLenum, :pointer ].freeze,
    glGetPixelMapfv:     [ :void, :GLenum, :pointer ].freeze,
    glGetPixelMapuiv:    [ :void, :GLenum, :pointer ].freeze,
    glGetPixelMapusv:    [ :void, :GLenum, :pointer ].freeze,
    glGetPolygonStipple: [ :void, :pointer ].freeze,
    glGetTexEnvfv:       [ :void, :GLenum, :GLenum, :pointer ].freeze,
    glGetTexEnviv:       [ :void, :GLenum, :GLenum, :pointer ].freeze,
    glGetTexGenfv:       [ :void, :GLenum, :GLenum, :pointer ].freeze,
    glGetTexGeniv:       [ :void, :GLenum, :GLenum, :pointer ].freeze,
    glIndexd:            [ :void, :GLdouble ].freeze,
    glIndexdv:           [ :void, :pointer ].freeze,
    glIndexf:            [ :void, :GLfloat ].freeze,
    glIndexfv:           [ :void, :pointer ].freeze,
    glIndexi:            [ :void, :GLint ].freeze,
    glIndexiv:           [ :void, :pointer ].freeze,
    glIndexs:            [ :void, :GLshort ].freeze,
    glIndexsv:           [ :void, :pointer ].freeze,
    glIndexMask:         [ :void, :GLuint ].freeze,
    glInitNames:         [ :void ].freeze,
    glIsList:            [ :GLboolean, :GLuint ].freeze,
    glLightf:            [ :void, :GLenum, :GLenum, :GLfloat ].freeze,
    glLightfv:           [ :void, :GLenum, :GLenum, :pointer ].freeze,
    glLighti:            [ :void, :GLenum, :GLenum, :GLint ].freeze,
    glLightiv:           [ :void, :GLenum, :GLenum, :pointer ].freeze,
    glLightModelf:       [ :void, :GLenum, :GLfloat ].freeze,
    glLightModelfv:      [ :void, :GLenum, :pointer ].freeze,
    glLightModeli:       [ :void, :GLenum, :GLint ].freeze,
    glLightModeliv:      [ :void, :GLenum, :pointer ].freeze,
    glLineStipple:       [ :void, :GLint, :GLushort ].freeze,
    glListBase:          [ :void, :GLuint ].freeze,
    glLoadIdentity:      [ :void ].freeze,
    glLoadMatrixd:       [ :void, :pointer ].freeze,
    glLoadMatrixf:       [ :void, :pointer ].freeze,
    glLoadName:          [ :void, :GLuint ].freeze,
    glMap1d:             [ :void, :GLenum, :GLdouble, :GLdouble, :GLint, :GLint, :pointer ].freeze,
    glMap1f:             [ :void, :GLenum, :GLfloat, :GLfloat, :GLint, :GLint, :pointer ].freeze,
    glMap2d:             [ :void, :GLenum, :GLdouble, :GLdouble, :GLint, :GLint, :GLdouble, :GLdouble, :GLint, :GLint, :pointer ].freeze,
    glMap2f:             [ :void, :GLenum, :GLfloat, :GLfloat, :GLint, :GLint, :GLfloat, :GLfloat, :GLint, :GLint, :pointer ].freeze,
    glMaterialf:         [ :void, :GLenum, :GLenum, :GLfloat ].freeze,
    glMaterialfv:        [ :void, :GLenum, :GLenum, :pointer ].freeze,
    glMateriali:         [ :void, :GLenum, :GLenum, :GLint ].freeze,
    glMaterialiv:        [ :void, :GLenum, :GLenum, :pointer ].freeze,
    glMatrixMode:        [ :void, :GLenum ].freeze,
    glMultMatrixd:       [ :void, :pointer ].freeze,
    glMultMatrixf:       [ :void, :pointer ].freeze,
    glNewList:           [ :void, :GLuint, :GLenum ].freeze,
    glNormal3b:          [ :void, :GLbyte, :GLbyte, :GLbyte ].freeze,
    glNormal3bv:         [ :void, :pointer ].freeze,
    glNormal3d:          [ :void, :GLdouble, :GLdouble, :GLdouble ].freeze,
    glNormal3dv:         [ :void, :pointer ].freeze,
    glNormal3f:          [ :void, :GLfloat, :GLfloat, :GLfloat ].freeze,
    glNormal3fv:         [ :void, :pointer ].freeze,
    glNormal3i:          [ :void, :GLint, :GLint, :GLint ].freeze,
    glNormal3iv:         [ :void, :pointer ].freeze,
    glNormal3s:          [ :void, :GLshort, :GLshort, :GLshort ].freeze,
    glNormal3sv:         [ :void, :pointer ].freeze,
    glOrtho:             [ :void, :GLdouble, :GLdouble, :GLdouble, :GLdouble, :GLdouble, :GLdouble ].freeze,
    glPassThrough:       [ :void, :GLfloat ].freeze,
    glPixelMapfv:        [ :void, :GLenum, :GLsizei, :pointer ].freeze,
    glPixelMapuiv:       [ :void, :GLenum, :GLsizei, :pointer ].freeze,
    glPixelMapusv:       [ :void, :GLenum, :GLsizei, :pointer ].freeze,
    glPixelTransferf:    [ :void, :GLenum, :GLfloat ].freeze,
    glPixelTransferi:    [ :void, :GLenum, :GLint ].freeze,
    glPixelZoom:         [ :void, :GLfloat, :GLfloat ].freeze,
    glPolygonStipple:    [ :void, :pointer ].freeze,
    glPopAttrib:         [ :void ].freeze,
    glPopMatrix:         [ :void ].freeze,
    glPopName:           [ :void ].freeze,
    glPushAttrib:        [ :void, :GLbitfield ].freeze,
    glPushMatrix:        [ :void ].freeze,
    glPushName:          [ :void, :GLuint ].freeze,
    glRasterPos2d:       [ :void, :GLdouble, :GLdouble ].freeze,
    glRasterPos2dv:      [ :void, :pointer ].freeze,
    glRasterPos2f:       [ :void, :GLfloat, :GLfloat ].freeze,
    glRasterPos2fv:      [ :void, :pointer ].freeze,
    glRasterPos2i:       [ :void, :GLint, :GLint ].freeze,
    glRasterPos2iv:      [ :void, :pointer ].freeze,
    glRasterPos2s:       [ :void, :GLshort, :GLshort ].freeze,
    glRasterPos2sv:      [ :void, :pointer ].freeze,
    glRasterPos3d:       [ :void, :GLdouble, :GLdouble, :GLdouble ].freeze,
    glRasterPos3dv:      [ :void, :pointer ].freeze,
    glRasterPos3f:       [ :void, :GLfloat, :GLfloat, :GLfloat ].freeze,
    glRasterPos3fv:      [ :void, :pointer ].freeze,
    glRasterPos3i:       [ :void, :GLint, :GLint, :GLint ].freeze,
    glRasterPos3iv:      [ :void, :pointer ].freeze,
    glRasterPos3s:       [ :void, :GLshort, :GLshort, :GLshort ].freeze,
    glRasterPos3sv:      [ :void, :pointer ].freeze,
    glRasterPos4d:       [ :void, :GLdouble, :GLdouble, :GLdouble, :GLdouble ].freeze,
    glRasterPos4dv:      [ :void, :pointer ].freeze,
    glRasterPos4f:       [ :void, :GLfloat, :GLfloat, :GLfloat, :GLfloat ].freeze,
    glRasterPos4fv:      [ :void, :pointer ].freeze,
    glRasterPos4i:       [ :void, :GLint, :GLint, :GLint, :GLint ].freeze,
    glRasterPos4iv:      [ :void, :pointer ].freeze,
    glRasterPos4s:       [ :void, :GLshort, :GLshort, :GLshort, :GLshort ].freeze,
    glRasterPos4sv:      [ :void, :pointer ].freeze,
    glRectd:             [ :void, :GLdouble, :GLdouble, :GLdouble, :GLdouble ].freeze,
    glRectdv:            [ :void, :pointer, :pointer ].freeze,
    glRectf:             [ :void, :GLfloat, :GLfloat, :GLfloat, :GLfloat ].freeze,
    glRectfv:            [ :void, :pointer, :pointer ].freeze,
    glRecti:             [ :void, :GLint, :GLint, :GLint, :GLint ].freeze,
    glRectiv:            [ :void, :pointer, :pointer ].freeze,
    glRects:             [ :void, :GLshort, :GLshort, :GLshort, :GLshort ].freeze,
    glRectsv:            [ :void, :pointer, :pointer ].freeze,
    glRenderMode:        [ :GLint, :GLenum ].freeze,
    glRotated:           [ :void, :GLdouble, :GLdouble, :GLdouble, :GLdouble ].freeze,
    glRotatef:           [ :void, :GLfloat, :GLfloat, :GLfloat, :GLfloat ].freeze,
    glScaled:            [ :void, :GLdouble, :GLdouble, :GLdouble ].freeze,
    glScalef:            [ :void, :GLfloat, :GLfloat, :GLfloat ].freeze,
    glSelectBuffer:      [ :void, :GLsizei, :pointer ].freeze,
    glShadeModel:        [ :void, :GLenum ].freeze,
    glTexCoord1d:        [ :void, :GLdouble ].freeze,
    glTexCoord1dv:       [ :void, :pointer ].freeze,
    glTexCoord1f:        [ :void, :GLfloat ].freeze,
    glTexCoord1fv:       [ :void, :pointer ].freeze,
    glTexCoord1i:        [ :void, :GLint ].freeze,
    glTexCoord1iv:       [ :void, :pointer ].freeze,
    glTexCoord1s:        [ :void, :GLshort ].freeze,
    glTexCoord1sv:       [ :void, :pointer ].freeze,
    glTexCoord2d:        [ :void, :GLdouble, :GLdouble ].freeze,
    glTexCoord2dv:       [ :void, :pointer ].freeze,
    glTexCoord2f:        [ :void, :GLfloat, :GLfloat ].freeze,
    glTexCoord2fv:       [ :void, :pointer ].freeze,
    glTexCoord2i:        [ :void, :GLint, :GLint ].freeze,
    glTexCoord2iv:       [ :void, :pointer ].freeze,
    glTexCoord2s:        [ :void, :GLshort, :GLshort ].freeze,
    glTexCoord2sv:       [ :void, :pointer ].freeze,
    glTexCoord3d:        [ :void, :GLdouble, :GLdouble, :GLdouble ].freeze,
    glTexCoord3dv:       [ :void, :pointer ].freeze,
    glTexCoord3f:        [ :void, :GLfloat, :GLfloat, :GLfloat ].freeze,
    glTexCoord3fv:       [ :void, :pointer ].freeze,
    glTexCoord3i:        [ :void, :GLint, :GLint, :GLint ].freeze,
    glTexCoord3iv:       [ :void, :pointer ].freeze,
    glTexCoord3s:        [ :void, :GLshort, :GLshort, :GLshort ].freeze,
    glTexCoord3sv:       [ :void, :pointer ].freeze,
    glTexCoord4d:        [ :void, :GLdouble, :GLdouble, :GLdouble, :GLdouble ].freeze,
    glTexCoord4dv:       [ :void, :pointer ].freeze,
    glTexCoord4f:        [ :void, :GLfloat, :GLfloat, :GLfloat, :GLfloat ].freeze,
    glTexCoord4fv:       [ :void, :pointer ].freeze,
    glTexCoord4i:        [ :void, :GLint, :GLint, :GLint, :GLint ].freeze,
    glTexCoord4iv:       [ :void, :pointer ].freeze,
    glTexCoord4s:        [ :void, :GLshort, :GLshort, :GLshort, :GLshort ].freeze,
    glTexCoord4sv:       [ :void, :pointer ].freeze,
    glTexEnvf:           [ :void, :GLenum, :GLenum, :GLfloat ].freeze,
    glTexEnvfv:          [ :void, :GLenum, :GLenum, :pointer ].freeze,
    glTexEnvi:           [ :void, :GLenum, :GLenum, :GLint ].freeze,
    glTexEnviv:          [ :void, :GLenum, :GLenum, :pointer ].freeze,
    glTexGend:           [ :void, :GLenum, :GLenum, :GLdouble ].freeze,
    glTexGendv:          [ :void, :GLenum, :GLenum, :pointer ].freeze,
    glTexGenf:           [ :void, :GLenum, :GLenum, :GLfloat ].freeze,
    glTexGenfv:          [ :void, :GLenum, :GLenum, :pointer ].freeze,
    glTexGeni:           [ :void, :GLenum, :GLenum, :GLint ].freeze,
    glTexGeniv:          [ :void, :GLenum, :GLenum, :pointer ].freeze,
    glTranslated:        [ :void, :GLdouble, :GLdouble, :GLdouble ].freeze,
    glTranslatef:        [ :void, :GLfloat, :GLfloat, :GLfloat ].freeze,
    glVertex2d:          [ :void, :GLdouble, :GLdouble ].freeze,
    glVertex2dv:         [ :void, :pointer ].freeze,
    glVertex2f:          [ :void, :GLfloat, :GLfloat ].freeze,
    glVertex2fv:         [ :void, :pointer ].freeze,
    glVertex2i:          [ :void, :GLint, :GLint ].freeze,
    glVertex2iv:         [ :void, :pointer ].freeze,
    glVertex2s:          [ :void, :GLshort, :GLshort ].freeze,
    glVertex2sv:         [ :void, :pointer ].freeze,
    glVertex3d:          [ :void, :GLdouble, :GLdouble, :GLdouble ].freeze,
    glVertex3dv:         [ :void, :pointer ].freeze,
    glVertex3f:          [ :void, :GLfloat, :GLfloat, :GLfloat ].freeze,
    glVertex3fv:         [ :void, :pointer ].freeze,
    glVertex3i:          [ :void, :GLint, :GLint, :GLint ].freeze,
    glVertex3iv:         [ :void, :pointer ].freeze,
    glVertex3s:          [ :void, :GLshort, :GLshort, :GLshort ].freeze,
    glVertex3sv:         [ :void, :pointer ].freeze,
    glVertex4d:          [ :void, :GLdouble, :GLdouble, :GLdouble, :GLdouble ].freeze,
    glVertex4dv:         [ :void, :pointer ].freeze,
    glVertex4f:          [ :void, :GLfloat, :GLfloat, :GLfloat, :GLfloat ].freeze,
    glVertex4fv:         [ :void, :pointer ].freeze,
    glVertex4i:          [ :void, :GLint, :GLint, :GLint, :GLint ].freeze,
    glVertex4iv:         [ :void, :pointer ].freeze,
    glVertex4s:          [ :void, :GLshort, :GLshort, :GLshort, :GLshort ].freeze,
    glVertex4sv:         [ :void, :pointer ].freeze
  } ).freeze
end